"""Where file bytes live — a seam, like PaymentProvider and Channel.

`LocalStorage` keeps files on disk for development and tests. A production
object store (S3, R2, GCS) is an account and a bill, so it drops in behind the
same three calls when one exists, without touching anything that decides what
may be stored or shown.

Keys are generated by the service, never taken from a filename: a key built
from user input is a path-traversal bug waiting for a "../" in an upload.
"""

import re
from pathlib import Path
from typing import Protocol

from app.core.config import settings

_KEY = re.compile(r"^[a-z0-9][a-z0-9/_-]{0,200}$")


class Storage(Protocol):
    provider: str
    bucket: str

    def put(self, key: str, data: bytes) -> None: ...
    def get(self, key: str) -> bytes: ...
    def delete(self, key: str) -> None: ...


class LocalStorage:
    provider = "local"

    def __init__(self, root: str | None = None) -> None:
        self.root = Path(root or settings.media_root).resolve()
        self.bucket = self.root.name

    def _path(self, key: str) -> Path:
        if not _KEY.match(key) or ".." in key:
            raise ValueError("invalid storage key")
        path = (self.root / key).resolve()
        if self.root not in path.parents:
            raise ValueError("storage key escapes the store")
        return path

    def put(self, key: str, data: bytes) -> None:
        path = self._path(key)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(data)

    def get(self, key: str) -> bytes:
        return self._path(key).read_bytes()

    def delete(self, key: str) -> None:
        self._path(key).unlink(missing_ok=True)


_storage: Storage | None = None


def storage() -> Storage:
    global _storage
    if _storage is None:
        _storage = LocalStorage()
    return _storage


def use(backend: Storage | None) -> None:
    """Swap the backend (tests; a future production adapter)."""
    global _storage
    _storage = backend
