"""Real, decodable images with private data planted in them (TASK-002 R3).

The C8 tests used hand-assembled marker sequences that no decoder would show
as a picture. These are generated by Pillow, open in any viewer, and then
carry the metadata a phone or an editing app would add — or an attacker would
hide. SECRET and GPS_TEXT are the strings no public byte may contain.
"""

import io
import struct
import zlib

from PIL import Image, ImageCms, PngImagePlugin

GPS_TEXT = b"GPSLatitude=52.229676;GPSLongitude=21.012229"
SECRET = b"PrivateAddress=ul. Tajna 17/4"


def leaks(data: bytes) -> bool:
    return any(s in data for s in (GPS_TEXT, SECRET, b"52.229676", b"Tajna"))


def _pattern(mode: str, size: tuple[int, int]) -> Image.Image:
    """A picture with structure, so encoders do real work."""
    w, h = size
    img = Image.new("RGB", size)
    img.putdata([((x * 7) % 256, (y * 5) % 256, ((x + y) * 3) % 256)
                 for y in range(h) for x in range(w)])
    return img if mode == "RGB" else img.convert(mode)


def seg(marker: int, payload: bytes) -> bytes:
    return b"\xff" + bytes([marker]) + struct.pack(">H", len(payload) + 2) + payload


def chunk(kind: bytes, body: bytes) -> bytes:
    return struct.pack(">I", len(body)) + kind + body + struct.pack(
        ">I", zlib.crc32(kind + body) & 0xFFFFFFFF)


def gps_exif(orientation: int | None = None) -> bytes:
    exif = Image.Exif()
    exif[0x010E] = SECRET.decode()            # ImageDescription
    exif[0x013B] = "Photographer at " + SECRET.decode()  # Artist
    if orientation:
        exif[0x0112] = orientation            # Orientation
    gps = exif.get_ifd(0x8825)
    gps[1] = "N"
    gps[2] = (52.0, 13.0, 47.0)
    gps[3] = "E"
    gps[4] = (21.0, 0.0, 44.0)
    return exif.tobytes()


def srgb_icc(description: bytes = b"") -> bytes:
    profile = ImageCms.ImageCmsProfile(ImageCms.createProfile("sRGB")).tobytes()
    # An ICC profile is a container: a hostile one carries whatever it likes.
    return profile + description


def jpeg(size=(64, 48), *, mode="RGB", exif=True, orientation=None, progressive=False,
         icc: bytes | None = None, extra_segments: bytes = b"", trailer: bytes = b"") -> bytes:
    out = io.BytesIO()
    kwargs = {"quality": 90, "progressive": progressive}
    if exif:
        kwargs["exif"] = gps_exif(orientation)
    if icc is not None:
        kwargs["icc_profile"] = icc
    _pattern(mode, size).save(out, "JPEG", **kwargs)
    data = out.getvalue()
    # Metadata segments right after SOI: XMP (APP1), IPTC (APP13), a comment.
    planted = (seg(0xE1, b"http://ns.adobe.com/xap/1.0/\x00" + GPS_TEXT)
               + seg(0xED, b"Photoshop 3.0\x00" + SECRET)
               + seg(0xFE, SECRET)
               + extra_segments)
    return data[:2] + planted + data[2:] + trailer


def png(size=(48, 32), *, mode="RGB", icc_name: bytes | None = None,
        extra_chunks: bytes = b"") -> bytes:
    out = io.BytesIO()
    info = PngImagePlugin.PngInfo()
    info.add_text("Comment", SECRET.decode())
    info.add_text("Location", GPS_TEXT.decode(), zip=True)                  # zTXt
    info.add_itxt("XML:com.adobe.xmp", GPS_TEXT.decode(), zip=False)       # iTXt
    _pattern(mode, size).save(out, "PNG", pnginfo=info)
    data = out.getvalue()
    head = data[:33]  # signature + IHDR
    rest = data[33:]
    planted = chunk(b"eXIf", b"MM\x00*" + GPS_TEXT) + extra_chunks
    if icc_name is not None:
        planted += chunk(b"iCCP", icc_name + b"\x00\x00" + zlib.compress(srgb_icc()))
    return head + planted + rest


def png_header_only(width: int, height: int) -> bytes:
    """A PNG whose header claims a size and whose pixels are a token IDAT —
    enough to test that the budget is enforced before decoding."""
    ihdr = struct.pack(">IIBBBBB", width, height, 8, 2, 0, 0, 0)
    return (b"\x89PNG\r\n\x1a\n" + chunk(b"IHDR", ihdr)
            + chunk(b"IDAT", zlib.compress(b"\x00" * 16)) + chunk(b"IEND", b""))


def other_format(fmt: str, size=(16, 16)) -> bytes:
    out = io.BytesIO()
    img = _pattern("RGB", size)
    if fmt == "GIF":
        img = img.convert("P")
    img.save(out, fmt)
    return out.getvalue()


def apng(frames: int = 2, size=(24, 24)) -> bytes:
    out = io.BytesIO()
    images = [_pattern("RGB", size).rotate(i * 90) for i in range(frames)]
    images[0].save(out, "PNG", save_all=True, append_images=images[1:])
    return out.getvalue()


def jpeg_segments(data: bytes) -> list[int]:
    """Marker codes of the header segments, up to and including SOS."""
    markers, i = [], 2
    while i + 4 <= len(data) and data[i] == 0xFF:
        marker = data[i + 1]
        markers.append(marker)
        if marker == 0xDA:
            break
        (length,) = struct.unpack(">H", data[i + 2:i + 4])
        i += 2 + length
    return markers


def png_chunks(data: bytes) -> list[bytes]:
    kinds, i = [], 8
    while i + 8 <= len(data):
        (length,) = struct.unpack(">I", data[i:i + 4])
        kinds.append(data[i + 4:i + 8])
        i += 12 + length
    return kinds
